management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /management
      path-mapping:
        health: health
        prometheus: metrics/prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    enable:
      http:
        server:
          requests: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.75,0.9,0.95,0.99
      sla:
        http.server.requests: 1s,5s
    tags:
      application: clinic-management-system
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
